version: "3.9"

services:
  app-back-blue:
    image: $DOCKERHUB_USERNAME/cloudnative-backend:latest
    environment:
      NODE_ENV: production
      DATABASE_URL: "postgresql://myuser:mypassword@db:5432/mydatabase"
    depends_on:
      - db

  app-front-blue:
    image: $DOCKERHUB_USERNAME/cloudnative-frontend:latest
    depends_on:
      - app-back-blue
